# Generated by Django 3.2.4 on 2021-06-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='A_description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cleints',
            name='c_description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='content',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
