# Generated by Django 3.2.4 on 2021-06-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210622_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='A2_description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='A3_description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
