# Generated by Django 3.2.4 on 2021-06-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210622_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='A2_description',
            new_name='Aa_description',
        ),
        migrations.RenameField(
            model_name='about_us',
            old_name='A3_description',
            new_name='Ab_description',
        ),
    ]
