# Generated by Django 3.2.4 on 2021-06-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210622_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleints',
            name='c_description',
        ),
    ]
