# Generated by Django 3.2.4 on 2021-06-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_cleints_c_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionality',
            name='main_heading',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
